version: '3'
services:
  backend:
    build: ./server
    container_name: wo-backend
    ports:
      - "5000:5000"
    networks:
      - webnet
    volumes:
      - ./server:/app
  frontend:
    build: ./client
    container_name: wo-frontend
    ports:
      - "3000:80"
    networks:
      - webnet
    depends_on:
      - backend
    volumes:
      - ./client:/app
  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet
networks:
  webnet:
    driver: bridge