services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./server
    container_name: backend
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=wo-backend.jembo.com
      - DB_USER=devadmin
      - DB_PASSWORD=devadmin
      - DB_NAME=wo_app
      - DB_PORT=3308
    restart: always
