version: '3.8'

services:
  client:
    build:
      context: ./client
    networks:
      - appnet

  server:
    build:
      context: ./server
    networks:
      - appnet

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - client
      - server
    restart: unless-stopped

networks:
  appnet:
    driver: bridge