version: "3.8"

services:
  client:
    container_name: wo_frontend
    build:
      context: ./client
    networks:
      - appnet
    environment:
      - VITE_APP_PORT=3000
      - VITE_API_BASE_URL=http://wo-backend.jembo.com:5000
    ports:
      - "3000:80"

  server:
    container_name: wo_backend
    build:
      context: ./server
    networks:
      - appnet
    environment:
      - PORT=5000
      - DB_HOST="wo-backend.jembo.com"
      - DB_USER="devadmin"
      - DB_PASSWORD="devadmin"
      - DB_NAME="wo_app"
      - DB_PORT=3306
    ports:
      - "5000:5000"

  nginx:
    container_name: wo_nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - client
      - server
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
