version: '3.8'

services:
  client:
    build:
      context: ./client
    networks:
      - appnet
    environment:
      - VITE_APP_PORT=3000
      - VITE_API_BASE_URL=http://wo-mt.jembo.com:5000

  server:
    build:
      context: ./server
    networks:
      - appnet
    environment:
      - PORT=5000
      - DB_HOST=192.168.10.15
      - DB_USER=devadmin
      - DB_PASSWORD=devadmin
      - DB_NAME=wo_app
      - DB_PORT=3306

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - client
      - server
    restart: unless-stopped

networks:
  appnet:
    driver: bridge