version: '3'
services:
  backend:
    build: ./server
    container_name: wo-backend
    ports:
      - "192.168.10.15:5000:5000"
    networks:
      - webnet
    volumes:
      - ./server:/app
  frontend:
    build: ./client
    container_name: wo-frontend
    ports:
      - "192.168.10.15:3000:3000"
    networks:
      - webnet
    depends_on:
      - backend
    volumes:
      - ./client:/app
  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "192.168.10.15:80:80"
      - "192.168.10.15:443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet
networks:
  webnet:
    driver: bridge