services:
  frontend:
    build: ./client
    container_name: wo_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./server
    container_name: wo_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=wo-backend.jembo.com
      - DB_USER=devadmin
      - DB_PASSWORD=devadmin
      - DB_NAME=wo_app
      - DB_PORT=3306
    restart: always
